version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  backend:
    build:
      context: ../SQRBackend # Adjust path to your backend project
      dockerfile: Dockerfile
    ports:
      - "5267:5000"
    volumes:
      - ../SQRBackend:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development